### ISSUE TITLE
Question: Transferring cart to logged in user

### ISSUE THREAD

**Issue by Riaan-ZA** [darryldecode/laravelshoppingcart#214]
I have persistent carts set up with DB storage. It's working fine for logged in users, but what I'd like to do is allow non logged in users to add to their cart and then require login for the checkout page. 

The problem is for this to happen I need to transfer the non logged in session cart to the newly logged in user. I'm thinking the way to do this is in the log in function, do a check if there is an existing cart, and if there is replace the users cart in the DB with that one. Problem is I'm not sure how to handle this transfer. Anyone got any suggestions (other than just looping though the items and re adding them to the logged in users cart)?

**Comment by darryldecode** [comment]
Hi. That is a business related scenario thus out of scope of the cart module. There might be different requirements along the transfer process so that you will have to code on your own design. There will be no other choice but to loop through the existing stateless cart and add to the "stateful" cart with the user's session. Best regards!
