### ISSUE TITLE
Database support.

### ISSUE THREAD

**Issue by HazeDevelopment** [darryldecode/laravelshoppingcart#22]
Do you mind adding database support beside session only?
we've encountered several session problems because of ajax calls adding and removing from the cart.

we'd like to have a backup to the database without having to do it manually on each call.
(preferable to do both sides, sessions and db, or make it optional)

Great work on the project though, we've been using it for quiet a while now!

kind regards,
Jurien Hamaker.

**Comment by darryldecode** [comment]
Hello @HazeDevelopment 

have you considered using events to deal with this things? It is more flexible and will have you more control of your data. For example, whenever an item has been added in the cart, there is an event triggered on that with the item and cart data passed on it, from there you can do whatever you want from that data like (on your case) save it on your shopping cart database as a record or anything.

For further info, take a look on:

https://github.com/darryldecode/laravelshoppingcart#events

Regards

**Comment by HazeDevelopment** [comment]
Thanks, that was all I needed to know!

**Comment by karandatwani92** [comment]
@KingsDevelopment @darryldecode 
Help required!!

Could you please give a coded example to use cart events in application with along with table schema for your cart object. I'm need to use this library for mobile application where JWT is used instead of sessions. It will be very helpful to everyone looking for the same.

Many Many thanks for your efforts.
