### ISSUE TITLE
Same product 2 times but with other size in CART

### ISSUE THREAD

**Issue by mucskaati** [darryldecode/laravelshoppingcart#69]
Hello,

When I add some item with size: XL and I want to add the same product but with other size for example L, the CART replace me first added product and the quantity will be change to 2 but size change to L.

I want 2 items in cart even it is the same product but one i want with size XL and one with size L.

Thanks for ur help.

**Comment by anonprophet** [comment]
if im understand u correctly,

u can merge the id with the size
ex: `41XL`

something like this
Cart::add($product->id . $product->options->size, $product->name, $product->price, 1, $options);

u now have 2 different item in cart

**Comment by mucskaati** [comment]
Thats it what I want! Thank u man

**Comment by matejsvajger** [comment]
@darryldecode I would suggest instead of using the item id, we would generate a unique id based on the item id and the contents of the attributes and store the cart item in the collection based on this new `rowid`.

We'd still preserve the ID field, but then we would use the rowid to update/remove the item.

Any thoughts on this?

**Comment by frezno** [comment]
ok, usually there is one unique part-number (sku) for each product, ie 

1234-1-1 = T-Shirt 1 Blue Medium
1234-1-2 = T-Shirt 1 Blue Large
1234-2-1 = T-Shirt 1 Red Medium
1234-2-2 = T-Shirt 1 Red Large
3456-1-1 = T-Shirt 2 Blue Medium
etc

in your database each product has its own row id

Doing it that way, where are the problems?

**Comment by matejsvajger** [comment]
Problem is, Customer usually doesn't have this data or doesn't provide it.

Sure we could rely on (sku) or make a custom implementation for generating a unique id before adding item to cart, but that means we would decouple logic that should be part of the cart on the outside.

When you install a package you want to be ready to go, not write a function to generate unique ids before moving on 😄 

I'd like to prepare a pull request, just want to iron out the details.

**Comment by frezno** [comment]
i see it the other way round, @matejsvajger 
you have to have correct data to run your business properly otherwise you will run into trouble sooner or later, usually sooner.
So why should a software be responsible for every possible idea a user might come up with?
A software has to be flexible to a certain point, sure, but imho there are limits to this.

**Comment by darryldecode** [comment]
@frezno @matejsvajger thanks for your input guys. Frenzo has a point, if you don't have that information in your products then there might be a problem on its data structures. It's a bit opinionated so we will leave it this way or until there is a much considerable reasons to change it 👍

**Comment by matejsvajger** [comment]
@darryldecode i agree with @frezno, data should be provided correctly from the start, but i still disagree the unique id should be handled outside.

Let's take the T-Shirt analogy further: You have a shirt of the same color and size BUT you offer a service to select a custom text printed on it. That is a product attribute and you can not have a possible unique sku, because the attribute is user generated.

How do you add two of this products with different text into Cart?

**Comment by frezno** [comment]
not really @matejsvajger

Let's take your example:
Customer wants T-Shirt Unicorn in Pink size Small for her daughter.
SKU is 12345-07-003

But she wants to have her daughters name printed on it.
Now it's no longer T Shirt 12345-07-003 but a unique one, which requires a unique SKU.
If you don't give it a unique SKU and another user orders T-Shirt 12345-07-003 what would he get, the regular Tee or the one which has the printed Charleen on it? Following your example/suggestion, it would be valid since they have the same SKU.

And how would you identify eg half a year later the product if customer asks you for a second T SHirt with named SKU? Would you deliver the standard one or the one with the printed name?

As soon as a product is different in any way to another product, i should get a unique SKU.
With that in mind you'll avoid lots of problems.

**Comment by matejsvajger** [comment]
@frezno I don't think the contents of the text is something you would track
with a SKU. No accounting software or POS system cares about that info. Nor
you have a printed shirt with the exact same text in the warehouse.

You would reference it with an order number where the details are stored
and order itself is used in the printshop when they print the name next to
the unicorn.

I like this package a lot, and I get that generating your own unique id is
not a lot of work, I just tought it would be a nice feature.

Cheers!


On 31 Jul 2017 7:23 pm, "frezno" <notifications@github.com> wrote:

not really @matejsvajger <https://github.com/matejsvajger>

Let's take your example:
Customer wants T-Shirt Unicorn in Pink size Small for her daughter.
SKU is 12345-07-003

But she wants to have her daughters name printed on it.
Now it's no longer T Shirt 12345-07-003 but a unique one, which requires a
unique SKU.
If you don't give it a unique SKU and another user orders T-Shirt
12345-07-003 what would he get, the regular Tee or the one which has the
printed Charleen on it? Following your example/suggestion, it would be
valid since they have the same SKU.

And how would you identify eg half a year later the product if customer
asks you for a second T SHirt with named SKU? Would you deliver the
standard one or the one with the printed name?

As soon as a product is different in any way to another product, i should
get a unique SKU.
With that in mind you'll avoid lots of problems.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/darryldecode/laravelshoppingcart/issues/69#issuecomment-319135496>,
or mute the thread

**Comment by darryldecode** [comment]
@matejsvajger if you only have the order # to identify unique product sales, how would you generate a detailed report like sales per product if you don't have SKU or any unique identifier of a unique product?

**Comment by matejsvajger** [comment]
@darryldecode We would still have a unique product id, we just don't have a 'unique SKU' - based on the 'customer text' written on the T-Shirt.
